/* export const fruitWords = [
    [
        { word: 'Apple', results: ['תפוח', 'חציל', 'תות', 'משמש'], correct: 'תפוח' },
        { word: 'Banana', results: ['בננה', 'מנגו', 'דובדבן', 'כרוב'], correct: 'בננה' },
        { word: 'Carrot', results: ['אבטיח', 'גזר', 'לימון', 'תפוח'], correct: 'גזר' },
        { word: 'Lemon', results: ['שסק', 'אגוז', 'שזיף', 'לימון'], correct: 'לימון' },
        { word: 'Lettuce', results: ['חסה', 'לימון', 'בננה', 'תפוח'], correct: 'חסה' },
        { word: 'Tomato', results: ['לימון', 'תפוז', 'עגבניה', 'מלפפון'], correct: 'עגבניה' },
        { word: 'Strawberry', results: ['תות', 'משמש', 'אפרסק', 'תאנה'], correct: 'תות' },
        { word: 'Cucumber', results: ['מלפפון', 'שזיף', 'כרובית', 'מנגו'], correct: 'מלפפון' },
        { word: 'Orange', results: ['כרוב', 'חסה', 'עגבניה', 'תפוז'], correct: 'תפוז' },
        { word: 'Onion', results: ['תפוז', 'שום', 'בצל', 'דובדבן'], correct: 'בצל' },
    ],
    [
        { word: 'Peach', results: ['מלון', 'תאנה', 'אפרסק', 'בצל'], correct: 'אפרסק' },
        { word: 'Grapes', results: ['בננה', 'ענבים', 'מנגו', 'אגוז'], correct: 'ענבים' },
        { word: 'Spinach', results: ['תפוז', 'תרד', 'כרוב', 'אבטיח'], correct: 'תרד' },
        { word: 'Garlic', results: ['שום', 'תפוח', 'לימון', 'אפרסק'], correct: 'שום' },
        { word: 'Pear', results: ['אגס', 'בננה', 'תפוח', 'מנגו'], correct: 'אגס' },
        { word: 'Pumpkin', results: ['דלעת', 'תפוח', 'תאנה', 'אפרסק'], correct: 'דלעת' },
        { word: 'Potato', results: ['פטריה', 'תפוז', 'תפוח אדמה', 'מנגו'], correct: 'תפוח אדמה' },
        { word: 'Mango', results: ['מנגו', 'שסק', 'אגוז', 'בננה'], correct: 'מנגו' },
        { word: 'Raspberry', results: ['תאנה', 'פטל', 'בצל', 'אגס'], correct: 'פטל' },
        { word: 'Cauliflower', results: ['כרובית', 'תפוז', 'תפוח', 'לימון'], correct: 'כרובית' },
    ],
    [
        { word: 'Avocado', results: ['אבוקדו', 'בצל', 'תפוז', 'אגוז'], correct: 'אבוקדו' },
        { word: 'Cherry', results: ['דובדבן', 'פטריה', 'תות', 'אפרסק'], correct: 'דובדבן' },
        { word: 'Pineapple', results: ['תפוז', 'אננס', 'ענבים', 'מנגו'], correct: 'אננס' },
        { word: 'Beet', results: ['חסה', 'תפוז', 'סלק', 'אפרסק'], correct: 'סלק' },
        { word: 'Blueberry', results: ['בננה', 'אוכמנייה', 'תפוח', 'אגס'], correct: 'אוכמנייה' },
        { word: 'Eggplant', results: ['תפוח', 'חציל', 'תאנה', 'אפרסק'], correct: 'חציל' },
        { word: 'Kiwi', results: ['קיווי', 'בננה', 'תפוח', 'מנגו'], correct: 'קיווי' },
        { word: 'Pomegranate', results: ['רימון', 'שסק', 'אגוז', 'בננה'], correct: 'רימון' },
        { word: 'Zucchini', results: ['תאנה', 'קישוא', 'בצל', 'אגס'], correct: 'קישוא' },
        { word: 'Broccoli', results: ['ברוקולי', 'תפוז', 'תפוח', 'לימון'], correct: 'ברוקולי' },
    ],
    [
        { word: 'Watermelon', results: ['תפוז', 'אבטיח', 'ענבים', 'מנגו'], correct: 'אבטיח' },
        { word: 'Fig', results: ['תאנה', 'פטריה', 'תות', 'אפרסק'], correct: 'תאנה' },
        { word: 'Coconut', results: ['קוקוס', 'בצל', 'תפוז', 'אגוז'], correct: 'קוקוס' },
        { word: 'Radish', results: ['חסה', 'תפוז', 'צנון', 'אפרסק'], correct: 'צנון' },
        { word: 'Raspberry', results: ['בננה', 'פטל', 'תפוח', 'אגס'], correct: 'פטל' },
        { word: 'Peanut', results: ['תפוח', 'בוטנים', 'תאנה', 'אפרסק'], correct: 'בוטנים' },
        { word: 'Celery', results: ['סלרי', 'בננה', 'תפוח', 'מנגו'], correct: 'סלרי' },
        { word: 'Apricot', results: ['משמש', 'שסק', 'אגוז', 'בננה'], correct: 'משמש' },
        { word: 'Asparagus', results: ['תאנה', 'אספרגוס', 'בצל', 'אגס'], correct: 'הלם' },
        { word: 'Artichoke', results: ['ארטישוק', 'תפוז', 'תפוח', 'לימון'], correct: 'ארטישוק' },
    ],
    [
        { word: 'plum', results: ['תפוח', 'תאנה', 'שזיף', 'בצל'], correct: 'שזיף' },
        { word: 'almond', results: ['שקד', 'פטריה', 'תות', 'אפרסק'], correct: 'שקד' },
        { word: 'grapefruit', results: ['תפוז', 'אשכולית', 'ענב', 'מנגו'], correct: 'אשכולית' },
        { word: 'cabbage', results: ['כרוב', 'תפוז', 'סלק', 'אפרסק'], correct: 'כרוב' },
        { word: 'blackberry', results: ['פטל שחור', 'בננה', 'תפוח', 'אגס'], correct: 'פטל שחור' },
        { word: 'corn', results: ['תירס', 'תפוח', 'תאנה', 'אפרסק'], correct: 'תירס' },
        { word: 'parsley', results: ['פטרוזיליה', 'בננה', 'תפוח', 'מנגו'], correct: 'פטרוזיליה' },
        { word: 'walnut', results: ['אגוז מלך', 'שסק', 'אגוז', 'בננה'], correct: 'אגוז מלך' },
        { word: 'rhubarb', results: ['רוברב', 'תאנה', 'בצל', 'אגס'], correct: 'רוברב' },
        { word: 'brussels sprouts', results: ['שאירבת בריסל', 'תפוז', 'תפוח', 'לימון'], correct: 'שאירבת בריסל' },
    ]
]; */


export const fruits = {
    title: 'פירות',
    words: [
        { en: "Apple", he: "תפוח", pronunciation: "אַפְּל" },
        { en: "Orange", he: "תפוז", pronunciation: "אוֹרֶנְג'" },
        { en: "Banana", he: "בננה", pronunciation: "בָּנָנָה" },
        { en: "Watermelon", he: "אבטיח", pronunciation: "ווֹטֶרְמֵלוֹן" },
        { en: "Tomato", he: "עגבניה", pronunciation: "טוֹמָאטוֹ" },
        { en: "Cucumber", he: "מלפפון", pronunciation: "קִיוּקַאמְבֵר" },
        { en: "Strawberry", he: "תות", pronunciation: "סְטרוֹבֵרִי" },
        { en: "Carrot", he: "גזר", pronunciation: "קֵרֶט" },
        { en: "Potato", he: "תפוח אדמה", pronunciation: "פּוֹטָאטוֹ" },
        { en: "Eggplant", he: "חציל", pronunciation: "אֵגְפְּלַאנְט" },
        { en: "Squash", he: "קישוא", pronunciation: "סְקווֹש" },
        { en: "Carob", he: "חרוב", pronunciation: "קֵרֵב" },
        { en: "Grapefruit", he: "אשכולית", pronunciation: "גְּרֵיפְרוּט" },
        { en: "Pineapple", he: "אננס", pronunciation: "פַּיְנַאפְּל" },
        { en: "Avocado", he: "אבוקדו", pronunciation: "אַבוֹקָדוֹ" },
        { en: "Cabbage", he: "כרוב", pronunciation: "קַאבֵיג'" },
        { en: "Pomegranate", he: "רימון", pronunciation: "פּוֹמֶגְרֶנֶט" },
        { en: "Date", he: "תמר", pronunciation: "דֵייט" },
        { en: "Clementine", he: "קלמנטינה", pronunciation: "קְלֶמֶנְטִין" },
        { en: "Kiwi", he: "קיווי", pronunciation: "קִיוִוִי" },
        { en: "Mango", he: "מנגו", pronunciation: "מַנְגו" },
        { en: "Plum", he: "שזיף", pronunciation: "פְּלֻם" },
        { en: "Persimmon", he: "אפרסמון", pronunciation: "פֶּרְסִימוֹן" },
        { en: "Pear", he: "אגס", pronunciation: "פֵּיר" },
        { en: "Almond", he: "שקד", pronunciation: "אַלְמוֹנְד" },
        { en: "Broccoli", he: "ברוקולי", pronunciation: "בְּרוֹקְלִי" },
        { en: "Corn", he: "תירס", pronunciation: "קוֹרְן" },
        { en: "Parsley", he: "פטרוזיליה", pronunciation: "פָּרְסְלֵי" },
        { en: "Onion", he: "בצל", pronunciation: "אוֹנְיוֹן" },
        { en: "Lychee", he: "ליצ'י", pronunciation: "לִיצ'ִי" },
        { en: "Pepper", he: "פלפל", pronunciation: "פֵּפֶר" },
        { en: "Pumpkin", he: "דלעת", pronunciation: "פּאמְפְּקִין" },
        { en: "Lettuce", he: "חסה", pronunciation: "לֶטִיס" },
        { en: "Garlic", he: "שום", pronunciation: "גָּרְלִיק" },
        { en: "Cilantro", he: "כוסברה", pronunciation: "סִילַאנְטְרו" },
        { en: "Lemon", he: "לימון", pronunciation: "לֶמוֹן" },
        { en: "Bean", he: "שעועית", pronunciation: "בִּין" },
        { en: "Fig", he: "תאנה", pronunciation: "פִיג" },
        { en: "Coconut", he: "קוקוס", pronunciation: "קוֹקוֹנַאט" },
        { en: "Pea", he: "אפונה", pronunciation: "פִּי" },
        { en: "Beet", he: "סלק", pronunciation: "בִּיט" },
        { en: "Wheat", he: "חיטה", pronunciation: "וִיט" },
        //{ en: "Cantaloupe", he: "מלון", pronunciation: "קַנְטָלוּפ" },
        { en: "Melon", he: "מלון", pronunciation: "קַנְטָלוּפ" },
        //{ en: "Zucchini", he: "קישוא", pronunciation: "זוּקִינִי" },
        { en: "Radish", he: "צנון", pronunciation: "רֵדִיש" },
        { en: "Celery", he: "סלרי", pronunciation: "סֶלֶרִי" },
        { en: "Spinach", he: "תרד", pronunciation: "סְפִינַאטצ'" },
        { en: "Mushroom", he: "פטריה", pronunciation: "מַשְׁרוּם" },
        { en: "Cauliflower", he: "כרוב לבן", pronunciation: "קוֹלִיפְלוֹר" },
        { en: "Raspberry", he: "פטל", pronunciation: "רַאסְבֵּרִי" },
        { en: "Blueberry", he: "תות שחור", pronunciation: "בְּלוּבֵּרִי" },
        { en: "Blackberry", he: "פטל שחור", pronunciation: "בְּלֵאקְבֵּרִי" },
        { en: "Cherry", he: "דובדבן", pronunciation: "צֵ׳רִי" },
        { en: "Peach", he: "אפרסק", pronunciation: "פִּיצ׳" },
        { en: "Apricot", he: "משמש", pronunciation: "אֵיְפְּרִיקוֹט" },
        { en: "Nectarine", he: "נקטרינה", pronunciation: "נֵקְטָרִין" },
    ]
};

export const vehicles = {
    title: "כלי רכב",
    words: [
        { en: "Car", he: "מכונית", pronunciation: "כָּר" },
        { en: "Motorcycle", he: "אופנוע", pronunciation: "מוֹטוֹרְסַיְקְל" },
        { en: "Bus", he: "אוטובוס", pronunciation: "בַּאס" },
        { en: "Train", he: "רכבת", pronunciation: "טְרֵיִן" },
        { en: "Truck", he: "משאית", pronunciation: "טְרַאק" },
        { en: "Bicycle", he: "אופניים", pronunciation: "בַּיְסִיקְל" },
        { en: "Plane", he: "מטוס", pronunciation: "פְּלֵיִן" },
        { en: "Ship", he: "ספינה", pronunciation: "שִׁיפ" },
        { en: "Boat", he: "סירה", pronunciation: "בּוֹט" },
        { en: "Helicopter", he: "מסוק", pronunciation: "הֶלִיקוֹפְּטֶר" },
        { en: "Submarine", he: "צוללת", pronunciation: "סַבמָרִין" },
        { en: "Tank", he: "טנק", pronunciation: "טֵינְק" },
        { en: "Tractor", he: "טרקטור", pronunciation: "טְרַאקְטוֹר" },
        { en: "Trailer", he: "גרורה", pronunciation: "טְרֵילֶר" },
        { en: "Ambulance", he: "אמבולנס", pronunciation: "אַמְבוּלַאנְס" },
        { en: "Fire Truck", he: "מכבה אש", pronunciation: "פַּיֵר טְרַאק" },
        { en: "Police Car", he: "מכונית משטרה", pronunciation: "פּוֹלִיס כָּר" },
        { en: "Taxi", he: "מונית", pronunciation: "טַאקְסִי" },
        { en: "Scooter", he: "קטנוע", pronunciation: "סְקוּטֶר" },
        { en: "Skateboard", he: "סקייטבורד", pronunciation: "סְקֵיְטְבּוֹרְד" },
        { en: "Hoverboard", he: "גלשן", pronunciation: "הוֹוֶרבוֹרְד" },
        { en: "Hot air balloon", he: "כדור פורח", pronunciation: "הוֹט אֵיֶר בַּלוּן" },
        { en: "Spaceship", he: "חללית", pronunciation: "סְפֵיִסשִיפ" },
        { en: "Ferry", he: "מעבורת", pronunciation: "פֶּרִי" },
        { en: "Limousine", he: "לימוזינה", pronunciation: "לִימוֹזִינָה" },
        { en: "Yacht", he: "יאכטה", pronunciation: "יָאט" },
        { en: "Cable car", he: "רכבל", pronunciation: "קֵיבֶל קָאר" },
        { en: "Forklift", he: "מנוף", pronunciation: "פוֹרקְלִיפְט" },
        { en: "Cargo ship", he: "ספינת משא", pronunciation: "קַארְגוֹ שִׁיפ" },
    ]
};

export const kitchenUtensils = {
    title: 'כלי מטבח',
    words: [
        { en: "Knife", he: "סכין", pronunciation: "נַיִף" },
        { en: "Fork", he: "מזלג", pronunciation: "פוֹרְק" },
        { en: "Spoon", he: "כף", pronunciation: "סְפוּן" },
        { en: "Bowl", he: "קערה", pronunciation: "בּוֹול" },
        { en: "Plate", he: "צלחת", pronunciation: "פְּלֵיט" },
        { en: "Glass", he: "כוס", pronunciation: "גְּלַאס" },
        { en: "Pot", he: "סיר", pronunciation: "פּוֹט" },
        { en: "Frying Pan", he: "מחבת", pronunciation: "פְּרַיִינְג פַּאן" },
        { en: "Oven", he: "תנור", pronunciation: "אָוֶן" },
        { en: "Microwave", he: "מיקרוגל", pronunciation: "מַיְקְרוֹווֶיב" },
        { en: "Blender", he: "מערבל", pronunciation: "בְּלֶנְדֶר" },
        { en: "Toaster", he: "טוסטר", pronunciation: "טוֹסְטֶר" },
        { en: "Mixer", he: "מיקסר", pronunciation: "מִיקְסֶר" },
        { en: "Kettle", he: "קומקום", pronunciation: "קֶטֶל" },
        { en: "Grater", he: "פומפיה", pronunciation: "גְּרֵיטֶר" },
        { en: "Chopping Board", he: "קרש חיתוך", pronunciation: "צ'ופִינְג בּוֹרְד" },
        { en: "Rolling Pin", he: "מערוך", pronunciation: "רוֹולִינְג פִּין" },
        { en: "Measuring Cup", he: "כוס מידה", pronunciation: "מֵז׳וּרִינְג קַאפ" },
        { en: "Whisk", he: "מטרפה", pronunciation: "ווִיסְק" },
        { en: "Spatula", he: "פלטה", pronunciation: "סְפָאטוּלָה" },
        { en: "Ladle", he: "מטען", pronunciation: "לֵיידֶל" },
        { en: "Colander", he: "נירה", pronunciation: "קוֹלַאנְדֶר" },
        { en: "Peeler", he: "מקלף", pronunciation: "פִּילֶר" },
        { en: "Can Opener", he: "פותחן פחיות", pronunciation: "קַאן אוֹפֶנֶר" },
        { en: "Baking Sheet", he: "תבנית אפיה", pronunciation: "בֵּיקִינְג שִיט" },
        { en: "Sieve", he: "מנית", pronunciation: "סִיב" },
        { en: "Grill", he: "גריל", pronunciation: "גְּרִיל" },
        { en: "Mortar and Pestle", he: "מְדֵכָה ואֲלֵית", pronunciation: "מוֹרְטַר אֲנָד פֵּסְטֶל" },
        { en: "Food Processor", he: "מעבד מזון", pronunciation: "פוּד פְּרוֹסֶסְּסוֹר" },
        { en: "Coffee Grinder", he: "טחנת קפה", pronunciation: "קוֹפִּי גְּרַיִנְדֶר" }
    ]
};

export const school = {
    title: 'בית ספר',
    words: [
        { en: "Teacher", he: "מורה", pronunciation: "טיצ'ר" },
        { en: "Student", he: "תלמיד", pronunciation: "סטוּדֶנט" },
        { en: "School", he: "בית ספר", pronunciation: "סקוּל" },
        { en: "Classroom", he: "כיתה", pronunciation: "קלַסרוּם" },
        { en: "Homework", he: "שיעורי בית", pronunciation: "הוֹמוְורק" },
        { en: "Lesson", he: "שיעור", pronunciation: "לֶסֶן" },
        { en: "Test", he: "מבחן", pronunciation: "טֶסט" },
        { en: "Grade", he: "ציון", pronunciation: "גְרֵיד" },
        { en: "Desk", he: "שולחן", pronunciation: "דֶסק" },
        { en: "Book", he: "ספר", pronunciation: "בּוּק" },
        { en: "Pen", he: "עט", pronunciation: "פֶּן" },
        { en: "Pencil", he: "עיפרון", pronunciation: "פֶנְסִיל" },
        { en: "Notebook", he: "מחברת", pronunciation: "נוֹוטְבוּק" },
        { en: "Blackboard", he: "לוח", pronunciation: "בְלַקְבוֹרד" },
        { en: "Chalk", he: "גיר", pronunciation: "צ'וֹק" },
        { en: "Eraser", he: "מחק", pronunciation: "אירֵיזֶר" },
        { en: "Ruler", he: "משולה", pronunciation: "רוּלֶר" },
        { en: "Backpack", he: "תיק גב", pronunciation: "בֵּקְפַּק" },
        { en: "Lunch", he: "ארוחת צהריים", pronunciation: "לַנץ'" },
        { en: "Recess", he: "הפסקה", pronunciation: "ריסֶס" },
        { en: "Study", he: "לימוד", pronunciation: "סטַדִּי" },
        { en: "Subject", he: "מקצוע", pronunciation: "סאבֶג'קט" },
        { en: "Principal", he: "מנהל", pronunciation: "פרינְסִיפַּל" },
        { en: "Librarian", he: "ספרן", pronunciation: "ליִברֵריאַן" },
        { en: "Janitor", he: "מנקה", pronunciation: "ג'ַניטּוֹר" },
        { en: "Textbook", he: "ספר לימוד", pronunciation: "טֶקסטְבּוּק" },
        { en: "Schedule", he: "לוח זמנים", pronunciation: "סקֶג'וּל" },
        { en: "Semester", he: "סמסטר", pronunciation: "סֶמֶסטֶר" },
        { en: "Report card", he: "תעודת הוראה", pronunciation: "ריפּוֹרט קַרד" },
        { en: "Project", he: "פרויקט", pronunciation: "פּרוֹג'ֶקט" },
        { en: "Quiz", he: "בחינה קצרה", pronunciation: "קווִיז" },
        { en: "Exam", he: "מבחן", pronunciation: "אֶקזָם" },
        { en: "Lecture", he: "הרצאה", pronunciation: "לֶקצ'ר" },
        { en: "Essay", he: "חיבור", pronunciation: "אֶסֵי" },
        { en: "Assignment", he: "משימה", pronunciation: "אַסַיינְמֶנט" },
        { en: "Calculator", he: "מחשבון", pronunciation: "קַלְקֻלֵיטּוֹר" },
        { en: "Locker", he: "ארון", pronunciation: "לֹקֶר" },
        { en: "Gym", he: "אולם ספורט", pronunciation: "ג'ים" },
        { en: "Library", he: "ספרייה", pronunciation: "לַיְבְרֶרִי" },
        { en: "Laboratory", he: "מעבדה", pronunciation: "לַאבּוֹרַטוֹרי" },
        { en: "Cafeteria", he: "חדר אוכל", pronunciation: "קַפֵּטֶרִיָה" },
        { en: "Playground", he: "מגרש משחקים", pronunciation: "פּלֵיְגרָאוּנד" },
        { en: "Auditorium", he: "אודיטוריום", pronunciation: "אָודִיטוֹרִיֻם" },
        { en: "Office", he: "משרד", pronunciation: "אֹפִיס" },
        { en: "Faculty", he: "סגל", pronunciation: "פַּקּוּלְטִי" },
        { en: "Dormitory", he: "מעונות", pronunciation: "דּוֹרְמִיטוֹרִי" },
        { en: "Tuition", he: "דמי לימוד", pronunciation: "טֻוּשֶן" },
    ]
};

export const toys = {
    title: 'צעצועים',
    words: [
        { en: "Doll", he: "בובה", pronunciation: "דּוֹל" },
        { en: "Action figure", he: "דמות פעולה", pronunciation: "אַקשֶן פִּיגּוּר" },
        { en: "Toy car", he: "מכונית צעצוע", pronunciation: "טוי קַר" },
        { en: "Puzzle", he: "פאזל", pronunciation: "פַּאזֶל" },
        { en: "Board game", he: "משחק לוח", pronunciation: "בוֹרד גֵיים" },
        { en: "Stuffed animal", he: "חיה ממולאה", pronunciation: "סְטַפּד אַנִימָל" },
        { en: "Lego", he: "לגו", pronunciation: "לֶגוֹ" },
        { en: "Blocks", he: "קוביות", pronunciation: "בְּלוֹקְס" },
        { en: "Playdough", he: "חימר פלסטלינה", pronunciation: "פְּלֵיְדוֹ" },
        { en: "Sandbox", he: "ארגז חול", pronunciation: "סַנדְבּוֹקְס" },
        { en: "Swing", he: "נדנדה", pronunciation: "סְווִינג" },
        { en: "Slide", he: "מגלשה", pronunciation: "סְלַיִד" },
        { en: "Bicycle", he: "אופניים", pronunciation: "בַּיִּסִקְל" },
        { en: "Skateboard", he: "סקייטבורד", pronunciation: "סְקֵיְטְבּוֹרד" },
        { en: "Tricycle", he: "אופני שלוש", pronunciation: "טְרַיִּסִקְל" },
        { en: "Roller skates", he: "גלגיליות", pronunciation: "רוֹלֶר סְקֵיְטְס" },
        { en: "Kite", he: "עפיפון", pronunciation: "קַיִּיט" },
        { en: "Yo-yo", he: "יו-יו", pronunciation: "יו-יו" },
        { en: "Remote control car", he: "מכונית שלט רחוק", pronunciation: "רִימוֹוט קוֹנטְרוֹל קַר" },
        { en: "Video game", he: "משחק וידאו", pronunciation: "וִידִיאוֹ גֵיים" },
        { en: "Rubber duck", he: "ברווז גומי", pronunciation: "רַאבֶּר דַאק" },
        { en: "Toy soldier", he: "חייל צעצוע", pronunciation: "טוי סוֹלג'ֶר" },
        { en: "Teddy bear", he: "דובי טדי", pronunciation: "טֶדִּי בֵּיר" },
        { en: "Puppet", he: "בובת בית קפה", pronunciation: "פַאפִּיט" },
        { en: "Marbles", he: "קליקרים", pronunciation: "מַארבֶּלס" },
        { en: "Train set", he: "רכבת צעצוע", pronunciation: "טרֵין סֶט" },
        { en: "Jigsaw puzzle", he: "פאזל של חיבורים", pronunciation: "ג'יגסו פַאזֶּל" },
        { en: "Building blocks", he: "קוביות בניה", pronunciation: "בִּילדִינג בְּלוֹקס" },
        { en: "Dollhouse", he: "בית בובות", pronunciation: "דוֹלהאוּס" },
        { en: "Bouncy ball", he: "כדור קופצני", pronunciation: "בָאוּנסי בּוֹל" },
        { en: "Plasticine", he: "פלסטלינה", pronunciation: "פְּלַסטִיסִין" },
        { en: "Model airplane", he: "דגם מטוס", pronunciation: "מוֹדֶל איירפְּליין" },
        { en: "Toy robot", he: "רובוט צעצוע", pronunciation: "טוי רוֹבוֹט" },
        { en: "Play tent", he: "אוהל משחק", pronunciation: "פְּלֵי טֶנט" },
        { en: "Hula hoop", he: "חולה-הופ", pronunciation: "הוּלה הוֹפ" },
        { en: "Scooter", he: "קורקינט", pronunciation: "סקוֹטֶר" },
        { en: "Bubble gun", he: "רובה של בועות", pronunciation: "בַאבֶּל גַאן" },
        { en: "Water gun", he: "מים רובה", pronunciation: "וָאטֶר גַאן" },
        { en: "Frisbee", he: "פריסבי", pronunciation: "פְּריסבִּי" },
        { en: "Jump rope", he: "חבל קפיצה", pronunciation: "ג'אמפ רוֹפ" },
    ]
};

export const professions = {
    title: 'בעלי מקצוע',
    words: [
        { en: "Doctor", he: "רופא", pronunciation: "דָאקְטֹר" },
        { en: "Teacher", he: "מורה", pronunciation: "טִיצ'ֶר" },
        { en: "Engineer", he: "מהנדס", pronunciation: "אֵנג'ִינִיר" },
        { en: "Carpenter", he: "נגר", pronunciation: "קַארפֶּנטֶר" },
        { en: "Chef", he: "שף", pronunciation: "שֶף" },
        { en: "Plumber", he: "אינסטלטור", pronunciation: "פְּלאמֶּר" },
        { en: "Lawyer", he: "עורך דין", pronunciation: "לויֶּר" },
        { en: "Pharmacist", he: "רוקח", pronunciation: "פַארמָסִיסט" },
        { en: "Dentist", he: "רופא שיניים", pronunciation: "דֶנטִיסט" },
        { en: "Veterinarian", he: "וְטֶרִינַאר", pronunciation: "וֶטֶרִינֶּרִיאן" },
        { en: "Journalist", he: "עיתונאי", pronunciation: "ג'אַרנָלִיסט" },
        { en: "Architect", he: "אדריכל", pronunciation: "אַרכֶּטֶקט" },
        { en: "Electrician", he: "חשמלאי", pronunciation: "אֵלֶקטרִישְׁיָן" },
        { en: "Painter", he: "צייר", pronunciation: "פֵיינְטֶר" },
        { en: "Mechanic", he: "מכונאי", pronunciation: "מֵכָאנִיק" },
        { en: "Policeman", he: "שוטר", pronunciation: "פוֹלִיסְמֵן" },
        { en: "Fireman", he: "כבאי", pronunciation: "פַיירְמֵן" },
        { en: "Actor", he: "שחקן", pronunciation: "אַקְטֹר" },
        { en: "Nurse", he: "אחות", pronunciation: "נֵרס" },
        { en: "Scientist", he: "מדען", pronunciation: "סַיינְטִיסט" },
        { en: "Barber", he: "ספר", pronunciation: "בַּארְבֵּר" },
        { en: "Waiter", he: "מלצר", pronunciation: "ווֵייטֶר" },
        { en: "Photographer", he: "צלם", pronunciation: "פוֹטוֹגְרָפֶר" },
        { en: "Pilot", he: "טייס", pronunciation: "פַּיְלוֹט" },
        { en: "Farmer", he: "חקלאי", pronunciation: "פַּארְמֶר" },
        { en: "Librarian", he: "ספרנית", pronunciation: "לִיבְרֵרִיאַן" },
        { en: "Tailor", he: "חייט", pronunciation: "טֵילוֹר" },
        { en: "Baker", he: "אופה", pronunciation: "בֵּייקֶר" },
        { en: "Soldier", he: "חייל", pronunciation: "סוֹלְג׳ֶר" },
        { en: "Musician", he: "מוזיקאי", pronunciation: "מוּזִישִׁיָן" },
        { en: "Bus Driver", he: "נהג אוטובוס", pronunciation: "בַּאס דְּרַיוֶר" },
        { en: "Janitor", he: "מנהל בית ספר", pronunciation: "ג׳ַנִיטוֹר" },
        { en: "Gardener", he: "גנן", pronunciation: "גַּארדֵּנֶר" },
        { en: "Postman", he: "דוור", pronunciation: "פּוֹסְטְמֵן" },
        { en: "Fisherman", he: "דייג", pronunciation: "פִּישֶרְמֵן" },
        { en: "Jeweler", he: "צורף", pronunciation: "ג׳וּאֶלֶר" },
        { en: "Builder", he: "בנאי", pronunciation: "בִּילדֶר" },
        { en: "Translator", he: "מתרגם", pronunciation: "טרַאנסְלֵיטוֹר" },
        { en: "Tour guide", he: "מדריך טיולים", pronunciation: "טוּר גַּיִיד" },
        { en: "Coach", he: "מאמן", pronunciation: "כּוֹץ'" },
    ]
};

export const musics = {
    title: 'כלי נגינה',
    words: [
        { en: "Piano", he: "פסנתר", pronunciation: "פִּיָאנוֹ" },
        { en: "Guitar", he: "גיטרה", pronunciation: "גִּיטָּאר" },
        { en: "Violin", he: "כינור", pronunciation: "וִיוֹלִין" },
        { en: "Drums", he: "תופים", pronunciation: "דְּרַאמְס" },
        { en: "Flute", he: "חליל", pronunciation: "פְּלוּט" },
        { en: "Saxophone", he: "סקסופון", pronunciation: "סֶקסוֹפוֹן" },
        { en: "Trumpet", he: "חצוצרה", pronunciation: "טְראֻמְפֵּט" },
        { en: "Cello", he: "צ'לו", pronunciation: "צֶ'לוֹ" },
        { en: "Harp", he: "נבל", pronunciation: "הַארְפּ" },
        { en: "Clarinet", he: "קלרינט", pronunciation: "קְלָרִינֵט" },
        { en: "Accordion", he: "אקורדיון", pronunciation: "אַקוֹרדְיוֹן" },
        { en: "Trombone", he: "טרומבון", pronunciation: "טְרוֹמְבוֹן" },
        { en: "Bass", he: "בס", pronunciation: "בֵּייס" },
        { en: "Banjo", he: "בנג'ו", pronunciation: "בַּנג'ו" },
        { en: "Ukulele", he: "אוקוללה", pronunciation: "יוּקָּלֵילֵי" },
        { en: "Mandolin", he: "מנדולינה", pronunciation: "מַנדוֹלִין" },
        { en: "Synthesizer", he: "סינתיסייזר", pronunciation: "סִינתֶ'סָּיֶזֶ'ר" },
        { en: "Harmonica", he: "מפוחית", pronunciation: "הַארְמוֹנִיקָה" },
        { en: "Tuba", he: "טובה", pronunciation: "טוּבָה" },
        { en: "Xylophone", he: "קסילופון", pronunciation: "זַּיְלוֹפוֹן" },
    ]
};

export const sweets = {
    title: 'ממתקים',
    words: [
        { en: "Chocolate", he: "שוקולית", pronunciation: "שוֹקוֹלִית" },
        { en: "Candy", he: "סוכריה", pronunciation: "קֶנדִּי" },
        { en: "Cake", he: "עוגה", pronunciation: "קֵיק" },
        { en: "Cookie", he: "עוגיה", pronunciation: "קוּקִּי" },
        { en: "Ice cream", he: "גלידה", pronunciation: "אַיִס קרִים" },
        { en: "Donut", he: "סופגניה", pronunciation: "דוֹנָט" },
        { en: "Cupcake", he: "עוגת כוס", pronunciation: "קַפְּקֵיק" },
        { en: "Marshmallow", he: "מרשמלו", pronunciation: "מַרשְמֶלו" },
        { en: "Jelly", he: "ג'לי", pronunciation: "גֶּ'לִּי" },
        { en: "Muffin", he: "מאפין", pronunciation: "מַאפִּין" },
        { en: "Brownie", he: "בראוני", pronunciation: "בְּרָאוּנִי" },
        { en: "Lollipop", he: "מסטיק", pronunciation: "לוֹלִיפּוֹפּ" },
        { en: "Gum", he: "מסטיק", pronunciation: "גַּאם" },
        { en: "Caramel", he: "קרמל", pronunciation: "קַרְאֵמֶל" },
        { en: "Pudding", he: "פודינג", pronunciation: "פֻּדִּינְג" },
        { en: "Truffle", he: "טראפל", pronunciation: "טְראַפְּל" },
        { en: "Praline", he: "פרלין", pronunciation: "פְּרָלִין" },
        { en: "Macaroon", he: "מקרון", pronunciation: "מַקָּרוּן" },
        { en: "Bonbon", he: "בונבון", pronunciation: "בוֹנבּוֹן" },
        { en: "Biscuit", he: "ביסקוויט", pronunciation: "בִּיסְקִּיט" },
        { en: "Waffle", he: "וופל", pronunciation: "וָפֶל" },
    ]
};

export const animals = {
    title: 'חיות',
    words: [
        { en: "Elephant", he: "פיל", pronunciation: "אֵלֶפֶּנְט" },
        { en: "Monkey", he: "קוף", pronunciation: "מָנקִי" },
        { en: "Giraffe", he: "ג'ירפה", pronunciation: "גִ'רָף" },
        { en: "Lion", he: "אריה", pronunciation: "לָיוֹן" },
        { en: "Tiger", he: "נמר", pronunciation: "טַיִגֶר" },
        { en: "Bear", he: "דוב", pronunciation: "בֵּר" },
        { en: "Zebra", he: "זברה", pronunciation: "זֵבְרָה" },
        { en: "Kangaroo", he: "קנגרו", pronunciation: "קַנגָּרוּ" },
        { en: "Penguin", he: "פינגווין", pronunciation: "פֶּנְגִ'וִין" },
        { en: "Hippopotamus", he: "היפופוטם", pronunciation: "הִיפּוֹפוֹטָמוּס" },
        { en: "Rhinoceros", he: "קרנף", pronunciation: "רַיינוֹסֵרוֹס" },
        { en: "Alligator", he: "תנין", pronunciation: "אַלִיגֵיְטֶר" },
        { en: "Peacock", he: "טווס", pronunciation: "פִּיקּוֹק" },
        { en: "Squirrel", he: "סנאי", pronunciation: "סְקווירֵל" },
        { en: "Koala", he: "דב קואלה", pronunciation: "קוֹאַלָה" },
        { en: "Flamingo", he: "פלמינגו", pronunciation: "פְלָמינגו" },
        { en: "Chameleon", he: "זיקית", pronunciation: "כַּמֵילִיאוֹן" },
        { en: "Shark", he: "כריש", pronunciation: "שַארְק" },
        { en: "Dolphin", he: "דולפין", pronunciation: "דוֹלְפִּין" },
        { en: "Whale", he: "לווייתן", pronunciation: "ווֵיל" },
        { en: "Octopus", he: "תמנון", pronunciation: "אוֹקְטוֹפּוּס" },
        { en: "Jellyfish", he: "מדוזה", pronunciation: "גֵ'לִיפִּישׁ" },
        { en: "Starfish", he: "כוכב ים", pronunciation: "סְטָרְפִּישׁ" },
        { en: "Seagull", he: "שחף", pronunciation: "סִיגַּל" },
        { en: "Eagle", he: "נשר", pronunciation: "אֵיגְּל" },
        { en: "Owl", he: "ינשוף", pronunciation: "אַוֹל" },
        { en: "Flamingo", he: "פלמינגו", pronunciation: "פְלָמינגו" },
        { en: "Swan", he: "ברבור", pronunciation: "סווֹן" },
        { en: "Penguin", he: "פינגווין", pronunciation: "פֶּנְגִ'וִין" },
        { en: "Pelican", he: "סקנאי", pronunciation: "פֵּלִיקָן" },
        { en: "Seal", he: "כלב ים", pronunciation: "סִיל" },
        { en: "Turtle", he: "צב", pronunciation: "טֶרטְּל" },
        { en: "Crab", he: "סרטן", pronunciation: "קרַאב" },
    ]
};

export const pets = {
    title: 'חיות בית',
    words: [
        { en: "Dog", he: "כלב", pronunciation: "דּוֹג" },
        { en: "Cat", he: "חתול", pronunciation: "קֵט" },
        { en: "Parrot", he: "תוכי", pronunciation: "פֵּרוֹט" },
        { en: "Hamster", he: "אוגר", pronunciation: "הַמְסטֶּר" },
        { en: "Fish", he: "דג", pronunciation: "פִּיש" },
        { en: "Turtle", he: "צב", pronunciation: "טֻרטְּל" },
        { en: "Rabbit", he: "ארנב", pronunciation: "רַאבִּיט" },
        { en: "Snake", he: "נחש", pronunciation: "סְנֵיק" },
        { en: "Ferret", he: "חמוס", pronunciation: "פֶּרֶט" },
        { en: "Iguana", he: "איגואנה", pronunciation: "אִיגוּאַנָה" },
        { en: "Canary", he: "כנרי", pronunciation: "קַנֵּרי" },
        { en: "Goldfish", he: "דג זהב", pronunciation: "גוֹלדפִּיש" },
        { en: "Hedgehog", he: "קיפוד", pronunciation: "הֵדגְּהוֹג" },
        { en: "Lizard", he: "לטאה", pronunciation: "לִיזַּרד" },
        { en: "Mouse", he: "עכבר", pronunciation: "מַאוּס" },
        { en: "Spider", he: "עכביש", pronunciation: "סְפָּיידֶּר" },
        { en: "Duck", he: "ברווז", pronunciation: "דַּק" },
        { en: "Chick", he: "אפרוח", pronunciation: "צ'יק" },
        { en: "Goat", he: "עז", pronunciation: "גוֹט" },
        { en: "Pigeon", he: "יונה", pronunciation: "פִּיג'ֵן" },
        { en: "Horse", he: "סוס", pronunciation: "הוֹרְס" },
        { en: "Chicken", he: "תרנגולת", pronunciation: "צ'יקֵּן" },
        { en: "Cow", he: "פרה", pronunciation: "קַאו" },
        { en: "Sheep", he: "כבשה", pronunciation: "שִׁיפ" },
        { en: "Frog", he: "צפרדע", pronunciation: "פְּרוֹג" },
        { en: "Snail", he: "שבלול", pronunciation: "סְנֵיל" },
        { en: "Squirrel", he: "סנאי", pronunciation: "סְקווִירֶל" },
    ]
};

export const clothings = {
    title: 'בגדים',
    words: [
        { en: "Shirt", he: "חולצה", pronunciation: "שֵרט" },
        { en: "Pants", he: "מכנסיים", pronunciation: "פַנטְס" },
        { en: "Dress", he: "שמלה", pronunciation: "דְּרֵס" },
        { en: "Skirt", he: "חצאית", pronunciation: "סְקֵרט" },
        { en: "Jacket", he: "מעיל", pronunciation: "גַ׳אֵקֶט" },
        { en: "Coat", he: "קוט", pronunciation: "קוֹט" },
        { en: "Tie", he: "עניבה", pronunciation: "טָי" },
        { en: "Socks", he: "גרביים", pronunciation: "סוֹקְס" },
        { en: "Shoes", he: "נעליים", pronunciation: "שוּז" },
        { en: "Hat", he: "כובע", pronunciation: "הֵאט" },
        { en: "Scarf", he: "צעיף", pronunciation: "סְקַארְף" },
        { en: "Gloves", he: "כפפות", pronunciation: "גְּלָאבְס" },
        { en: "Belt", he: "חגורה", pronunciation: "בֵּלט" },
        { en: "Underwear", he: "לבנים", pronunciation: "אַנְדֶרווֵּר" },
        { en: "Pajamas", he: "פיג'מה", pronunciation: "פַּגְ׳אָמָה" },
        { en: "Sweater", he: "סוודר", pronunciation: "סְווֶטֶר" },
        { en: "Jeans", he: "ג'ינס", pronunciation: "גֵ'ינְס" },
        { en: "Sunglasses", he: "משקפי שמש", pronunciation: "סַנגְלָאסֵּס" },
        { en: "Boots", he: "מגפיים", pronunciation: "בוּטְס" },
        { en: "Suit", he: "חליפה", pronunciation: "סוּט" },
        { en: "Sandals", he: "סנדלים", pronunciation: "סַנדַּלְס" },
        { en: "Slippers", he: "נעלי בית", pronunciation: "סְלִיפֶּרס" },
        { en: "Swimsuit", he: "בגד ים", pronunciation: "סווימסוּט" },
        { en: "Raincoat", he: "מעיל גשם", pronunciation: "רֵינקוֹט" },
        { en: "Uniform", he: "מדים", pronunciation: "יוּנִיפוֹרם" },
        { en: "Bathrobe", he: "חלוק אמבטיה", pronunciation: "בַּאתְרוֹב" },
        { en: "Earmuffs", he: "מחממי אוזניים", pronunciation: "אִירמַּאףְס" },
        { en: "Cap", he: "כובע קסקט", pronunciation: "כַּאפּ" },
        { en: "Flip-flops", he: "כפכפים", pronunciation: "פְּלִיפ-פְּלָאפְס" },
        { en: "Apron", he: "סינר", pronunciation: "אֵייפְרוֹן" },
    ]
};

export const countries = {
    title: 'מדינות',
    words: [
        { en: "Australia", he: "אוסטרליה", pronunciation: "אוֹסטרַליָה" },
        { en: "Brazil", he: "ברזיל", pronunciation: "בְּרָזִיל" },
        { en: "Canada", he: "קנדה", pronunciation: "קַנָּדָה" },
        { en: "Denmark", he: "דנמרק", pronunciation: "דֵּנמַרק" },
        { en: "Egypt", he: "מצרים", pronunciation: "אֵגְזיפְּט" },
        { en: "France", he: "צרפת", pronunciation: "פְּרַאנְס" },
        { en: "Germany", he: "גרמניה", pronunciation: "גֵּרמַני" },
        { en: "Holland", he: "הולנד", pronunciation: "הָאלַנְד" },
        { en: "Italy", he: "איטליה", pronunciation: "אִיטָלִי" },
        { en: "Japan", he: "יפן", pronunciation: "גֵּפַן" },
        { en: "Kenya", he: "קניה", pronunciation: "קֵּניא" },
        { en: "Lebanon", he: "לבנון", pronunciation: "לֵּבַנוֹן" },
        { en: "Mexico", he: "מקסיקו", pronunciation: "מֵּקסִיקו" },
        { en: "Norway", he: "נורווגיה", pronunciation: "נוֹרווֵי" },
        { en: "Peru", he: "פרו", pronunciation: "פֵּרוּ" },
        { en: "Qatar", he: "קטאר", pronunciation: "קַטַּאר" },
        { en: "Russia", he: "רוסיה", pronunciation: "רַשְּׁיה" },
        { en: "Spain", he: "ספרד", pronunciation: "סְפֵּיין" },
        { en: "Turkey", he: "טורקיה", pronunciation: "טַרקִי" },
        { en: "United Kingdom", he: "בריטניה", pronunciation: "יוּנַּייטֵד קִינְגְדוֹם" },
        { en: "Vietnam", he: "ויאטנם", pronunciation: "וִיאֶטְנַאם" },
        { en: "Zimbabwe", he: "זימבבואה", pronunciation: "זִימַבַּאווֵ" },
    ]
};

export const colors = {
    title: 'צבעים',
    words: [
        { en: "Red", he: "אדום", pronunciation: "אָדוֹם" },
        { en: "Blue", he: "כחול", pronunciation: "כָּחוֹל" },
        { en: "Yellow", he: "צהוב", pronunciation: "צָהוֹב" },
        { en: "Green", he: "ירוק", pronunciation: "יָרוֹק" },
        { en: "Black", he: "שחור", pronunciation: "שָׁחוֹר" },
        { en: "White", he: "לבן", pronunciation: "לָבָן" },
        { en: "Pink", he: "ורוד", pronunciation: "וָרוֹד" },
        { en: "Purple", he: "סגול", pronunciation: "סָגוֹל" },
        { en: "Brown", he: "חום", pronunciation: "חוּם" },
        { en: "Gray", he: "אפור", pronunciation: "אָפוֹר" },
        { en: "Orange", he: "כתום", pronunciation: "כָּתוֹם" },
        { en: "Burgundy", he: "בורדו", pronunciation: "בּוֹרדּוֹ" },
        { en: "Turquoise", he: "טורקיז", pronunciation: "טוּרקִיז" },
        { en: "Beige", he: "בז'", pronunciation: "בֶּז׳" },
    ]
};

export const furniture = {
    title: 'רהיטים',
    words: [
        { en: "Chair", he: "כיסא", pronunciation: "צְ'יֵיר" },
        { en: "Table", he: "שולחן", pronunciation: "טֵיבֶל" },
        { en: "Bed", he: "מיטה", pronunciation: "בֶּד" },
        { en: "Desk", he: "מספר", pronunciation: "דֵּסק" },
        { en: "Sofa", he: "ספה", pronunciation: "סוֹפָה" },
        { en: "Cabinet", he: "ארון", pronunciation: "קַאבִּינֶט" },
        { en: "Shelf", he: "מדף", pronunciation: "שֶּלף" },
        { en: "Drawer", he: "מגירה", pronunciation: "דְרוּאֵר" },
        { en: "Bedside table", he: "שידה", pronunciation: "בֶּדסַיֵיד טֵיבֶל" },
        { en: "Wardrobe", he: "ארונית", pronunciation: "וָרדְרוֹב" },
        { en: "Bookcase", he: "ספריה", pronunciation: "בוּקקֵייס" },
        { en: "Armchair", he: "כיסא זרועות", pronunciation: "אַרמְצֵ'ייר" },
        { en: "Stool", he: "ספסל", pronunciation: "סְטוּל" },
        { en: "Cupboard", he: "ארונית מטבח", pronunciation: "קַאפְבּוֹרד" },
        { en: "Couch", he: "ספה", pronunciation: "קַאוץ'" },
        { en: "Ottoman", he: "פוף", pronunciation: "אוֹטוֹמַן" },
        { en: "Bench", he: "ספסל", pronunciation: "בֶּנץ'" },
        { en: "Bunk bed", he: "מיטת קומותיים", pronunciation: "בַּאנק בֶּד" },
        { en: "Futon", he: "פוטון", pronunciation: "פְיוּטוֹן" },
        { en: "Recliner", he: "כיסא משענת", pronunciation: "רִיקלִיינֵר" },
        { en: "Sideboard", he: "ארונית", pronunciation: "סַיידְבוֹרד" },
        { en: "Hutch", he: "ארון תצוגה", pronunciation: "הַאץ'" },
        { en: "Wing chair", he: "כיסא כנפיים", pronunciation: "ווִינג צֵ'ייר" },
        { en: "Rocking chair", he: "כיסא נדנדה", pronunciation: "רוֹקינג צֵ'ייר" },
        { en: "Bar stool", he: "כיסא בר", pronunciation: "בַּר סְטוּל" },
        { en: "Loveseat", he: "ספה זוגית", pronunciation: "לָאבסִיט" },
        { en: "Credenza", he: "ארון משרדי", pronunciation: "קְרדנְזָה" },
    ]
};



